import { Inter } from "next/font/google";
import Navigation from "../Components/Navigation";
import Head from "next/head";

 // import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;




import "./globals.css";
import "./css/header.css";


export const metadata = {
  title: "Create Bange App",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">     
      <body>            
          <Navigation />
          

          {children}
          <footer>
            Footer
          </footer>
      </body>
    </html>
  );
}
