import { Inter } from "next/font/google";
import Navigation from "../Components/Navigation";
import Head from "next/head";


import "./globals.css";
import "./main.css";


export const metadata = {
  title: "Create Bange App",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">  
      <body>            
          <Navigation />
          {children}
          <footer>
            Footer
          </footer>
      </body>
    </html>
  );
}
